#configMode: 1
#CommandsTime:
#  "00:05": # Обязательно писать такой формат: HH:mm, не 0:5, не 00:5, не 0:05, а именно 00:05 
#    - "say На сервере используется плагин BeefTimeCommand"
#    - "say Создатель плагина: https://vk.com/id550519736"
#
configMode: 2
CommandsTime:
  sunday:
    "00:05":  
      - "say На сервере используется плагин TimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
  monday:
    "00:05": 
      - "say На сервере используется плагин BeefTimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
  tuesday:
    "00:05":
      - "say На сервере используется плагин BeefTimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
  wednesday:
    "00:05": 
      - "say На сервере используется плагин BeefTimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
  thursday:
    "00:05":
      - "say На сервере используется плагин BeefTimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
  friday:
    "00:05": 
      - "say На сервере используется плагин BeefTimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
  saturday:
    "00:05":
      - "say На сервере используется плагин BeefTimeCommand"
      - "say Создатель плагина: https://vk.com/id550519736"
