name: BeefTimeCommand
version: 1.1.1
main: ru.whitebeef.timecommandbeef.Main
api-version: 1.13
author: WhiteBeef
commands:
  plancommand:
    usage: /<command> <time> <plancommand>
    description: Запланировать команду
    permission: beeftimecommand.plancommand
permissions:
  beeftimecommand.plancommand:
    description: Использование команды /plancommand
    default: op