name: BeefTimeCommand
version: 1.2.1
main: ru.whitebeef.timecommandbeef.Main
api-version: 1.13
author: WhiteBeef
commands:
  plancommand:
    usage: /<command> <time> <plancommand>
    description: Запланировать команду
    permission: beeftimecommand.plancommand
  plancommandfrom:
    usage: /<command> <timefrom> <time> <plancommand>
    description: Запланировать команду начиная с какого-то времени
    permission: beeftimecommand.plancommandfrom
  repeatcommand:
      usage: /<command> <starttime> <repeattime> <plancommand>
      description: Запланировать повторяющуюся команду
      permission: beeftimecommand.repeatcommand
permissions:
  beeftimecommand.plancommand:
    description: Использование команды /plancommand
    default: op
  beeftimecommand.repeatcommand:
    description: Запланировать команду
    default: op
  beeftimecommand.plancommandfrom:
    description: Использование команды /plancommandfrom
    default: op
